<a href="https://colab.research.google.com/github/Bayaniblues/Lambda-pre-assignments/blob/master/004-numpy" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Lambda School Data Science - Intro to Python  
---
# Assignment 04 - Intro to `numpy`
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_assign4"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!

---


## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [0]:
# Import numpy and assign it the standard alias
import numpy as np
import random

In [0]:
xarray = np.array([2, 5, 7, 8])
for x in range(0,2):
  smallest = np.amin(xarray, axis=0) # identifies smallest value from array
  xarray = np.delete(xarray, np.where(xarray == smallest))
  print(xarray)

[5 7 8]
[7 8]


### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [0]:
# Generate your random numbers
myarray = np.random.randint(100, size=(5, 3))


# myarray = random.randrange(1, 100, 2))
print(myarray)


[[81 46 38]
 [46 18  5]
 [59 39  7]
 [59 17 79]
 [ 8 68  2]]


### 1.3 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [0]:
# 1. Return the first row:
myarray[0,:]

array([31, 97, 50])

In [0]:
# 2. Return the last column
myarray[:,-1]

array([50, 86, 36, 63, 52])

In [0]:
# 3. Return the third column values from the 4th and 5th rows
# [colum : row, range]
myarray[3:5,2]

array([88, 13])

In [0]:
# 4. Multiply every value in the array by 2
np.dot(myarray, 2)


array([[162,  92,  76],
       [ 92,  36,  10],
       [118,  78,  14],
       [118,  34, 158],
       [ 16, 136,   4]])

In [0]:
# 5. Divide every value by 3
np.divide(myarray, 3)



array([[27.        , 15.33333333, 12.66666667],
       [15.33333333,  6.        ,  1.66666667],
       [19.66666667, 13.        ,  2.33333333],
       [19.66666667,  5.66666667, 26.33333333],
       [ 2.66666667, 22.66666667,  0.66666667]])

In [0]:
# 6. Increase the values in the first row by 12
myarray[0,:] + 12


array([93, 58, 50])

In [0]:
# 7. Calculate the mean of the first column
np.mean(myarray[0,:])


55.0

In [0]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
print(myarray)
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
print(myarray)
# remove two smallest values
myarray = myarray[2:]
print(myarray)
# calculate the median
np.median(myarray)

[81]
[81]
[]


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [0]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
myarray = np.random.randint(100, size=(5, 3))

print(myarray)
print(np.std(myarray))

[[26  9 21]
 [40 11 10]
 [57 88 94]
 [ 9 85 79]
 [68 80 25]]
31.822842948632562


In [0]:
# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True

for x in myarray[:,1]:
  if (x > 25):
    print("True")
  else:
    print('False')

# Apply the mask


False
False
True
True
True


In [0]:
# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
np.less(myarray, [40])

# apply the mask


array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False],
       [ True, False, False],
       [False, False,  True]])

### Solution 1.3: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [0]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[40 85 49]
 [66 27 61]
 [53 61 30]
 [72 94 69]
 [11 42 11]]


1. The first row:  [40 85 49]


2. The last column:  [49 61 30 69 11]


3. The 3rd column, 4th & 5th rows:  [69 11]


4. Multiply by 2: 
 [[ 80 170  98]
 [132  54 122]
 [106 122  60]
 [144 188 138]
 [ 22  84  22]]


5. Divide by 3: 
 [[13.33333333 28.33333333 16.33333333]
 [22.          9.         20.33333333]
 [17.66666667 20.33333333 10.        ]
 [24.         31.33333333 23.        ]
 [ 3.66666667 14.          3.66666667]]


6. Add 12 to the first row: 
 [52 97 61]


7. The mean of the 1st column:  48.4


8. The median after removing the 2 smallest values:  61.0


9. The standard deviation is:  28.582995894779604


10. All values in 2nd column > 25: 
 [[17 31 65]
 [44 69 81]]


11. All values < 40: 
 [17 31 21  3 19 14  5  9]


---
### Submit your assignment notebook! (Make sure you've changed the name to FIRSTNAME_LASTNAME_assign4): 

1.  Click the Share button in the upper-right hand corner of the notebook.
2.  Get the shareable link.
3.  Set condition to: "Anyone with the link can comment."

---